---
# Source: website-map/templates/pull_secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson:
---
# Source: website-map/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: website-map-secrets
  namespace: test
type: Opaque
data:
  github-secret: "eA=="
  github-client-id: "eA=="
  github-install-id: "eA=="
---
# Source: website-map/templates/get_content.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: get-content
  namespace: test
data:
  get_content.py: |
    import sys
    import time
    import jwt
    import requests
    import os

    pem = "/secrets/gh"
    client_id = os.environ["GH_CLIENT_ID"]
    install_id = os.environ["GH_INSTALL_ID"]
    owner = "nycmeshnet"
    repo = "nycmesh.net"
    branch = "master"
    workflow_name = "Build distribution artifact for map.nycmesh.net"
    artifact_path = "/content/new_content.zip"

    def get_jwt():
        with open(pem, 'rb') as pem_file:
            signing_key = pem_file.read()

        payload = {
            'iat': int(time.time()),
            'exp': int(time.time()) + 600,
            'iss': client_id
        }

        encoded_jwt = jwt.encode(payload, signing_key, algorithm='RS256')
        return encoded_jwt

    def get_install_token():
        token = get_jwt()

        url = f"https://api.github.com/app/installations/{install_id}/access_tokens"
        res = requests.post(url, headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "X-GitHub-Api-Version": "2022-11-28",
        })
        return res.json()["token"]

    def select_artifact():
        token = get_install_token()
        url = f"https://api.github.com/repos/{owner}/{repo}/actions/runs?branch={branch}&status=success"
        res = requests.get(url, headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "X-GitHub-Api-Version": "2022-11-28",
        })
        latest_workflow_id = None
        for workflow_run in res.json()["workflow_runs"]:
            status = workflow_run["status"]
            conclusion = workflow_run["conclusion"]
            if workflow_run["name"] == workflow_name and status == "completed" and conclusion == "success":
                latest_workflow_id = workflow_run["id"]
                break

        if latest_workflow_id is None:
            print("Did not find workflow")
            exit(1)

        # Get artifacts
        url = f"https://api.github.com/repos/{owner}/{repo}/actions/runs/{latest_workflow_id}/artifacts"
        res = requests.get(url, headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "X-GitHub-Api-Version": "2022-11-28",
        })
        artifact_name = res.json()["artifacts"][0]["name"]
        if artifact_name != "map-site-build":
            print(f"Unexpected artifact name {artifact_name}")
            exit(1)
        artifact_download_url = res.json()["artifacts"][0]["archive_download_url"]
        with requests.get(artifact_download_url, allow_redirects=True, stream=True, headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "X-GitHub-Api-Version": "2022-11-28",
        }) as res:
            with open(artifact_path, "wb") as fd:
                for chunk in res.iter_content(chunk_size=2048):
                    fd.write(chunk)

    if __name__ == "__main__":
        select_artifact()
---
# Source: website-map/templates/nginx_config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: test
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        off;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        server {
          listen       80;
          server_name  localhost;

          #access_log  /var/log/nginx/host.access.log  main;

          location / {
              root   /content/current;
              index  index.html;
              error_page 404 /404.html;
              rewrite ^/nodes/(.*) /index.html last;
              add_header Strict-Transport-Security "max-age=2628000" always;
              add_header X-Frame-Options "SAMEORIGIN" always;
              add_header X-Content-Type-Options "nosniff" always;
              add_header Referrer-Policy "no-referrer" always;
              add_header Permissions-Policy "accelerometer=(), ambient-light-sensor=(), autoplay=(), camera=(), display-capture=(), document-domain=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), interest-cohort=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=()" always;
          }
        }
    }
---
# Source: website-map/templates/scripts.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  namespace: test
data:
  map.entrypoint.sh: |
    echo "Startup"
    pip install requests PyJWT cryptography
    apk add bash git nodejs npm curl zip jq
    echo "Installing hugo"
    HUGO_VERSION="0.69.2"
    curl -sLo "/tmp/hugo.tgz" "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
    tar -xzf /tmp/hugo.tgz
    chmod a+x /hugo
    mv /hugo /usr/bin/hugo
    echo "Installing dart-saas"
    npm install -g sass
    echo "First manual run of update map"
    bash /map.update.sh
    echo "*/10 * * * * /bin/bash /map.update.sh" >> /etc/crontabs/root
    echo "Starting cron"
    crond -f -L /proc/1/fd/1 -l 4
    echo "Error: Cron exited"
  map.build.zip.sh: |
    if [ -d /workspace ]; then
      rm -rf /workspace
    fi
    git clone --recursive https://github.com/nycmeshnet/nycmesh.net /workspace
    cd /workspace
    export STANDALONE_MAP_BUILD="true"
    export NODE_OPTIONS='--openssl-legacy-provider'
    sh update-map.sh
    export HUGO_ENVIRONMENT="production"
    export HUGO_CACHEDIR="/tmp/hugo_cache"
    hugo --minify --baseURL "https://nycmesh.net/"
    echo "Build Map Payload"
    mkdir -p public/map/img/
    mv public/img/map/ public/map/img/map/
    mv public/favicon.ico public/map/favicon.ico
    mv public/404.html public/map/
    echo "Make zip"
    if [ -f "/content/new_content.zip" ]; then
      rm /content/new_content.zip
    fi
    cd public/map
    zip -r /content/new_content.zip .
  map.update.sh: |
    #!/bin/bash
    echo "Updating content"
    if [ ! -z "$BUILD_MAP" ]; then
      echo "building map"
      bash /map.build.zip.sh
    else
      echo "downloading map"
      python3 /get_content.py
    fi
    echo "Update counter"
    content_dir="/content/current"
    counter_file="/content/counter"
    if [ ! -f "$counter_file" ]; then
      echo "0" > "$counter_file"
    fi
    counter=$(cat "$counter_file")
    ((counter++))
    echo "$counter" > "$counter_file"
    echo "Counter is $counter"
    if [ "$counter" -gt "500" ]; then
      echo "Reset counter"
      rm -f $counter_file
      rm -rf $content_dir
    fi
    echo "Unpacking content"
    content_zip="/content/new_content.zip"
    unzip -o $content_zip -d $content_dir
    echo "Cleanup"
    rm -f $content_zip
    # Cleanup downloaded content
---
# Source: website-map/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-map-data
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
# Source: website-map/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-website-map-backend
  labels:
    helm.sh/chart: website-map-0.1.0
    app.kubernetes.io/name: website-map
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: website-map
    app.kubernetes.io/instance: release-name
---
# Source: website-map/templates/backend.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-website-map-backend
  namespace: test
  labels:
    helm.sh/chart: website-map-0.1.0
    app.kubernetes.io/name: website-map
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: website-map
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app: backend
        helm.sh/chart: website-map-0.1.0
        app.kubernetes.io/name: website-map
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        {}
      containers:
        - name: website-map-backend
          securityContext:
            {}
          image: "docker.io/nginx@sha256:c15da6c91de8d2f436196f3a768483ad32c258ed4e1beb3d367a27ed67253e66"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: content-vol
              mountPath: /content
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          resources:
            {}
      initContainers:
        - name: update-map-cron
          image: "docker.io/python@sha256:f80206d96683c1b27cd522dc300f791a48362b895ad5c0bdd26f78f853c76fa5"
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          command: ['sh', '/map.entrypoint.sh']
          env:
            - name: GH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: website-map-secrets
                  key: github-client-id
            - name: GH_INSTALL_ID
              valueFrom:
                secretKeyRef:
                  name: website-map-secrets
                  key: github-install-id
            - name: BUILD_MAP
              value: "true"
          volumeMounts:
            - name: content-vol
              mountPath: /content
            - name: map-entrypoint
              mountPath: /map.entrypoint.sh
              subPath: map.entrypoint.sh
              readOnly: true
            - name: map-build-zip
              mountPath: /map.build.zip.sh
              subPath: map.build.zip.sh
              readOnly: true
            - name: get-content
              mountPath: /get_content.py
              subPath: get_content.py
              readOnly: true
            - name: map-update
              mountPath: /map.update.sh
              subPath: map.update.sh
              readOnly: true
            - mountPath: "/secrets/gh"
              subPath: github-secret
              name: github-secret
              readOnly: true
      volumes:
        - name: content-vol
          persistentVolumeClaim:
            claimName: website-map-data
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: map-entrypoint
          configMap:
            name: scripts
            items:
              - key: map.entrypoint.sh
                path: map.entrypoint.sh
        - name: map-update
          configMap:
            name: scripts
            items:
              - key: map.update.sh
                path: map.update.sh
        - name: map-build-zip
          configMap:
            name: scripts
            items:
              - key: map.build.zip.sh
                path: map.build.zip.sh
        - name: get-content
          configMap:
            name: get-content
            items:
              - key: get_content.py
                path: get_content.py
        - name: github-secret
          secret:
            secretName: website-map-secrets
            items:
              - key: github-secret
                path: github-secret
---
# Source: website-map/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-website-map
  namespace: test
  labels:
    helm.sh/chart: website-map-0.1.0
    app.kubernetes.io/name: website-map
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: map.nycmesh.net
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: release-name-website-map-backend
                port:
                  number: 80
