apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  namespace: {{ .Values.app_namespace }}
data:
  map.entrypoint.sh: |
    echo "Startup"
    echo "Initial content download"
    sh /map.update.sh
    echo "Starting cron"
    crond -f
    echo "Error: Cron exited"
  map.update.sh: |
    echo "Updating content"
    # Download content
    echo "Unpacking content"
    # Unpack
    echo "Validating content"
    # Sanity check
    echo "Cut over content"
    # Cut over
    echo "Cleanup"
    # Cleanup downloaded content
