apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  namespace: {{ .Values.app_namespace }}
data:
  map.entrypoint.sh: |
    echo "Startup"
    pip install requests PyJWT cryptography
    echo "Initial content download"
    sh /map.update.sh
    echo "*/10 * * * * /bin/sh /map.update.sh" >> /etc/crontabs/root
    echo "Starting cron"
    crond -f
    echo "Error: Cron exited"
  map.update.sh: |
    echo "Updating content"
    python3 /get_content.py
    echo "Unpacking content"
    # Unpack
    echo "Validating content"
    # Sanity check
    echo "Cut over content"
    # Cut over
    echo "Cleanup"
    # Cleanup downloaded content
