apiVersion: v1
kind: Secret
metadata:
  name: website-map-secrets
  namespace: {{ .Values.app_namespace }}
type: Opaque
data:
  github-secret: {{ .Values.github_secret | b64enc | quote }}
  github-client-id: {{ .Values.github_client_id | b64enc | quote }}
  github-install-id: {{ .Values.github_install_id | b64enc | quote }}
