apiVersion: v1
kind: Service
metadata:
  name: {{ include "website-map.fullname" . }}-backend
  labels:
    {{- include "website-map.labels" . | nindent 4 }}
  namespace: {{ .Values.app_namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "website-map.selectorLabels" . | nindent 4 }}
