backend:
  replicaCount: 1
  image:
    repository: docker.io/nginx
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
  enableReadinessProbe: false
  readinessProbeInitialDelaySeconds: 20
  enableLivenessProbe: false
  livenessProbeInitialDelaySeconds: 20
  livenessProbePeriodSeconds: 15
  resources: {}

cron:
  image:
    repository: docker.io/python
    pullPolicy: IfNotPresent
    tag: "3.13-alpine"

imageCredentials:
  registry: docker.io

pvc_name: "website-map-data"
pvc_size: "1Gi"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
